### ISSUE TITLE
Training time of Math23k for an epoch?

### ISSUE THREAD

**Issue by GrangerLue** [ShichaoSun/math_seq2tree#3]
Hi, 

May I ask how long did you train Math23K for an epoch? Your paper did not mention the concrete training time. 

I tried to reimplement this paper. My dataset (4936 instances) needs around 10 min to run an epoch (I modified the data loader as it is kind of outdated), does that make sense? 

Thank you

**Comment by ShichaoSun** [comment]
Sorry, I forgot the exact training time because I conducted the experiments too long time ago. It may take no more than an hour to run an epoch on Math23K dataset using GTX 1080Ti.  I am not very sure. And I vaguely remember the fact that it takes no more than 12 hours to conduct 5-fold crossing validation on Math23K under the setting in this paper. Hope this information can help you!  

Lastly, I think it is reasonable to cost 10 min to run an epoch for the dataset (4836 instances). If you can pre-process the data and then use the dataloader to construct tensor from the pre-processed data, the training time may be reduced.

**Comment by GrangerLue** [comment]
> Sorry, I forgot the exact training time because I conducted the experiments too long time ago. It may take no more than an hour to run an epoch on Math23K dataset using GTX 1080Ti. I am not very sure. And I vaguely remember the fact that it takes no more than 12 hours to conduct 5-fold crossing validation on Math23K under the setting in this paper. Hope this information can help you!
> 
> Lastly, I think it is reasonable to cost 10 min to run an epoch for the dataset (4836 instances). If you can pre-process the data and then use the dataloader to construct tensor from the pre-processed data, the training time may be reduced.

thanks :)
